[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.11",
    "rich>=13.9.4",
    "trafilatura>=2.0.0",
    "twilio>=9.4.4",
    "yt-dlp>=2025.1.26",
]
